<?php

class CountriesTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('countries')->truncate();
        
		\DB::table('countries')->insert(array (
			0 => 
			array (
				'id' => '4',
				'name' => 'Afghanistan',
				'iso_alpha2' => 'AF',
				'iso_alpha3' => 'AFG',
				'iso_numeric' => '4',
				'currency_code' => 'AFN',
				'currency_name' => 'Afghani',
				'currrency_symbol' => '؋',
				'flag' => 'AF.png',
			),
			1 => 
			array (
				'id' => '5',
				'name' => 'Albania',
				'iso_alpha2' => 'AL',
				'iso_alpha3' => 'ALB',
				'iso_numeric' => '8',
				'currency_code' => 'ALL',
				'currency_name' => 'Lek',
				'currrency_symbol' => 'Lek',
				'flag' => 'AL.png',
			),
			2 => 
			array (
				'id' => '6',
				'name' => 'Algeria',
				'iso_alpha2' => 'DZ',
				'iso_alpha3' => 'DZA',
				'iso_numeric' => '12',
				'currency_code' => 'DZD',
				'currency_name' => 'Dinar',
				'currrency_symbol' => NULL,
				'flag' => 'DZ.png',
			),
			3 => 
			array (
				'id' => '7',
				'name' => 'American Samoa',
				'iso_alpha2' => 'AS',
				'iso_alpha3' => 'ASM',
				'iso_numeric' => '16',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'AS.png',
			),
			4 => 
			array (
				'id' => '8',
				'name' => 'Andorra',
				'iso_alpha2' => 'AD',
				'iso_alpha3' => 'AND',
				'iso_numeric' => '20',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'AD.png',
			),
			5 => 
			array (
				'id' => '9',
				'name' => 'Angola',
				'iso_alpha2' => 'AO',
				'iso_alpha3' => 'AGO',
				'iso_numeric' => '24',
				'currency_code' => 'AOA',
				'currency_name' => 'Kwanza',
				'currrency_symbol' => 'Kz',
				'flag' => 'AO.png',
			),
			6 => 
			array (
				'id' => '10',
				'name' => 'Anguilla',
				'iso_alpha2' => 'AI',
				'iso_alpha3' => 'AIA',
				'iso_numeric' => '660',
				'currency_code' => 'XCD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'AI.png',
			),
			7 => 
			array (
				'id' => '11',
				'name' => 'Antarctica',
				'iso_alpha2' => 'AQ',
				'iso_alpha3' => 'ATA',
				'iso_numeric' => '10',
				'currency_code' => '',
				'currency_name' => '',
				'currrency_symbol' => NULL,
				'flag' => 'AQ.png',
			),
			8 => 
			array (
				'id' => '12',
				'name' => 'Antigua and Barbuda',
				'iso_alpha2' => 'AG',
				'iso_alpha3' => 'ATG',
				'iso_numeric' => '28',
				'currency_code' => 'XCD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'AG.png',
			),
			9 => 
			array (
				'id' => '13',
				'name' => 'Argentina',
				'iso_alpha2' => 'AR',
				'iso_alpha3' => 'ARG',
				'iso_numeric' => '32',
				'currency_code' => 'ARS',
				'currency_name' => 'Peso',
				'currrency_symbol' => '$',
				'flag' => 'AR.png',
			),
			10 => 
			array (
				'id' => '14',
				'name' => 'Armenia',
				'iso_alpha2' => 'AM',
				'iso_alpha3' => 'ARM',
				'iso_numeric' => '51',
				'currency_code' => 'AMD',
				'currency_name' => 'Dram',
				'currrency_symbol' => NULL,
				'flag' => 'AM.png',
			),
			11 => 
			array (
				'id' => '15',
				'name' => 'Aruba',
				'iso_alpha2' => 'AW',
				'iso_alpha3' => 'ABW',
				'iso_numeric' => '533',
				'currency_code' => 'AWG',
				'currency_name' => 'Guilder',
				'currrency_symbol' => 'ƒ',
				'flag' => 'AW.png',
			),
			12 => 
			array (
				'id' => '16',
				'name' => 'Australia',
				'iso_alpha2' => 'AU',
				'iso_alpha3' => 'AUS',
				'iso_numeric' => '36',
				'currency_code' => 'AUD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'AU.png',
			),
			13 => 
			array (
				'id' => '17',
				'name' => 'Austria',
				'iso_alpha2' => 'AT',
				'iso_alpha3' => 'AUT',
				'iso_numeric' => '40',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'AT.png',
			),
			14 => 
			array (
				'id' => '18',
				'name' => 'Azerbaijan',
				'iso_alpha2' => 'AZ',
				'iso_alpha3' => 'AZE',
				'iso_numeric' => '31',
				'currency_code' => 'AZN',
				'currency_name' => 'Manat',
				'currrency_symbol' => 'ман',
				'flag' => 'AZ.png',
			),
			15 => 
			array (
				'id' => '19',
				'name' => 'Bahamas',
				'iso_alpha2' => 'BS',
				'iso_alpha3' => 'BHS',
				'iso_numeric' => '44',
				'currency_code' => 'BSD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'BS.png',
			),
			16 => 
			array (
				'id' => '20',
				'name' => 'Bahrain',
				'iso_alpha2' => 'BH',
				'iso_alpha3' => 'BHR',
				'iso_numeric' => '48',
				'currency_code' => 'BHD',
				'currency_name' => 'Dinar',
				'currrency_symbol' => NULL,
				'flag' => 'BH.png',
			),
			17 => 
			array (
				'id' => '21',
				'name' => 'Bangladesh',
				'iso_alpha2' => 'BD',
				'iso_alpha3' => 'BGD',
				'iso_numeric' => '50',
				'currency_code' => 'BDT',
				'currency_name' => 'Taka',
				'currrency_symbol' => NULL,
				'flag' => 'BD.png',
			),
			18 => 
			array (
				'id' => '22',
				'name' => 'Barbados',
				'iso_alpha2' => 'BB',
				'iso_alpha3' => 'BRB',
				'iso_numeric' => '52',
				'currency_code' => 'BBD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'BB.png',
			),
			19 => 
			array (
				'id' => '23',
				'name' => 'Belarus',
				'iso_alpha2' => 'BY',
				'iso_alpha3' => 'BLR',
				'iso_numeric' => '112',
				'currency_code' => 'BYR',
				'currency_name' => 'Ruble',
				'currrency_symbol' => 'p.',
				'flag' => 'BY.png',
			),
			20 => 
			array (
				'id' => '24',
				'name' => 'Belgium',
				'iso_alpha2' => 'BE',
				'iso_alpha3' => 'BEL',
				'iso_numeric' => '56',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'BE.png',
			),
			21 => 
			array (
				'id' => '25',
				'name' => 'Belize',
				'iso_alpha2' => 'BZ',
				'iso_alpha3' => 'BLZ',
				'iso_numeric' => '84',
				'currency_code' => 'BZD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => 'BZ$',
				'flag' => 'BZ.png',
			),
			22 => 
			array (
				'id' => '26',
				'name' => 'Benin',
				'iso_alpha2' => 'BJ',
				'iso_alpha3' => 'BEN',
				'iso_numeric' => '204',
				'currency_code' => 'XOF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'BJ.png',
			),
			23 => 
			array (
				'id' => '27',
				'name' => 'Bermuda',
				'iso_alpha2' => 'BM',
				'iso_alpha3' => 'BMU',
				'iso_numeric' => '60',
				'currency_code' => 'BMD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'BM.png',
			),
			24 => 
			array (
				'id' => '28',
				'name' => 'Bhutan',
				'iso_alpha2' => 'BT',
				'iso_alpha3' => 'BTN',
				'iso_numeric' => '64',
				'currency_code' => 'BTN',
				'currency_name' => 'Ngultrum',
				'currrency_symbol' => NULL,
				'flag' => 'BT.png',
			),
			25 => 
			array (
				'id' => '29',
				'name' => 'Bolivia',
				'iso_alpha2' => 'BO',
				'iso_alpha3' => 'BOL',
				'iso_numeric' => '68',
				'currency_code' => 'BOB',
				'currency_name' => 'Boliviano',
				'currrency_symbol' => '$b',
				'flag' => 'BO.png',
			),
			26 => 
			array (
				'id' => '30',
				'name' => 'Bosnia and Herzegovina',
				'iso_alpha2' => 'BA',
				'iso_alpha3' => 'BIH',
				'iso_numeric' => '70',
				'currency_code' => 'BAM',
				'currency_name' => 'Marka',
				'currrency_symbol' => 'KM',
				'flag' => 'BA.png',
			),
			27 => 
			array (
				'id' => '31',
				'name' => 'Botswana',
				'iso_alpha2' => 'BW',
				'iso_alpha3' => 'BWA',
				'iso_numeric' => '72',
				'currency_code' => 'BWP',
				'currency_name' => 'Pula',
				'currrency_symbol' => 'P',
				'flag' => 'BW.png',
			),
			28 => 
			array (
				'id' => '32',
				'name' => 'Bouvet Island',
				'iso_alpha2' => 'BV',
				'iso_alpha3' => 'BVT',
				'iso_numeric' => '74',
				'currency_code' => 'NOK',
				'currency_name' => 'Krone',
				'currrency_symbol' => 'kr',
				'flag' => 'BV.png',
			),
			29 => 
			array (
				'id' => '33',
				'name' => 'Brazil',
				'iso_alpha2' => 'BR',
				'iso_alpha3' => 'BRA',
				'iso_numeric' => '76',
				'currency_code' => 'BRL',
				'currency_name' => 'Real',
				'currrency_symbol' => 'R$',
				'flag' => 'BR.png',
			),
			30 => 
			array (
				'id' => '34',
				'name' => 'British Indian Ocean Territory',
				'iso_alpha2' => 'IO',
				'iso_alpha3' => 'IOT',
				'iso_numeric' => '86',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'IO.png',
			),
			31 => 
			array (
				'id' => '35',
				'name' => 'British Virgin Islands',
				'iso_alpha2' => 'VG',
				'iso_alpha3' => 'VGB',
				'iso_numeric' => '92',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'VG.png',
			),
			32 => 
			array (
				'id' => '36',
				'name' => 'Brunei',
				'iso_alpha2' => 'BN',
				'iso_alpha3' => 'BRN',
				'iso_numeric' => '96',
				'currency_code' => 'BND',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'BN.png',
			),
			33 => 
			array (
				'id' => '37',
				'name' => 'Bulgaria',
				'iso_alpha2' => 'BG',
				'iso_alpha3' => 'BGR',
				'iso_numeric' => '100',
				'currency_code' => 'BGN',
				'currency_name' => 'Lev',
				'currrency_symbol' => 'лв',
				'flag' => 'BG.png',
			),
			34 => 
			array (
				'id' => '38',
				'name' => 'Burkina Faso',
				'iso_alpha2' => 'BF',
				'iso_alpha3' => 'BFA',
				'iso_numeric' => '854',
				'currency_code' => 'XOF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'BF.png',
			),
			35 => 
			array (
				'id' => '39',
				'name' => 'Burundi',
				'iso_alpha2' => 'BI',
				'iso_alpha3' => 'BDI',
				'iso_numeric' => '108',
				'currency_code' => 'BIF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'BI.png',
			),
			36 => 
			array (
				'id' => '40',
				'name' => 'Cambodia',
				'iso_alpha2' => 'KH',
				'iso_alpha3' => 'KHM',
				'iso_numeric' => '116',
				'currency_code' => 'KHR',
				'currency_name' => 'Riels',
				'currrency_symbol' => '៛',
				'flag' => 'KH.png',
			),
			37 => 
			array (
				'id' => '41',
				'name' => 'Cameroon',
				'iso_alpha2' => 'CM',
				'iso_alpha3' => 'CMR',
				'iso_numeric' => '120',
				'currency_code' => 'XAF',
				'currency_name' => 'Franc',
				'currrency_symbol' => 'FCF',
				'flag' => 'CM.png',
			),
			38 => 
			array (
				'id' => '3',
				'name' => 'Canada',
				'iso_alpha2' => 'CA',
				'iso_alpha3' => 'CAN',
				'iso_numeric' => '124',
				'currency_code' => 'CAD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'CA.png',
			),
			39 => 
			array (
				'id' => '42',
				'name' => 'Cape Verde',
				'iso_alpha2' => 'CV',
				'iso_alpha3' => 'CPV',
				'iso_numeric' => '132',
				'currency_code' => 'CVE',
				'currency_name' => 'Escudo',
				'currrency_symbol' => NULL,
				'flag' => 'CV.png',
			),
			40 => 
			array (
				'id' => '43',
				'name' => 'Cayman Islands',
				'iso_alpha2' => 'KY',
				'iso_alpha3' => 'CYM',
				'iso_numeric' => '136',
				'currency_code' => 'KYD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'KY.png',
			),
			41 => 
			array (
				'id' => '44',
				'name' => 'Central African Republic',
				'iso_alpha2' => 'CF',
				'iso_alpha3' => 'CAF',
				'iso_numeric' => '140',
				'currency_code' => 'XAF',
				'currency_name' => 'Franc',
				'currrency_symbol' => 'FCF',
				'flag' => 'CF.png',
			),
			42 => 
			array (
				'id' => '45',
				'name' => 'Chad',
				'iso_alpha2' => 'TD',
				'iso_alpha3' => 'TCD',
				'iso_numeric' => '148',
				'currency_code' => 'XAF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'TD.png',
			),
			43 => 
			array (
				'id' => '46',
				'name' => 'Chile',
				'iso_alpha2' => 'CL',
				'iso_alpha3' => 'CHL',
				'iso_numeric' => '152',
				'currency_code' => 'CLP',
				'currency_name' => 'Peso',
				'currrency_symbol' => NULL,
				'flag' => 'CL.png',
			),
			44 => 
			array (
				'id' => '47',
				'name' => 'China',
				'iso_alpha2' => 'CN',
				'iso_alpha3' => 'CHN',
				'iso_numeric' => '156',
				'currency_code' => 'CNY',
				'currency_name' => 'Yuan Renminbi',
				'currrency_symbol' => '¥',
				'flag' => 'CN.png',
			),
			45 => 
			array (
				'id' => '48',
				'name' => 'Christmas Island',
				'iso_alpha2' => 'CX',
				'iso_alpha3' => 'CXR',
				'iso_numeric' => '162',
				'currency_code' => 'AUD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'CX.png',
			),
			46 => 
			array (
				'id' => '49',
				'name' => 'Cocos Islands',
				'iso_alpha2' => 'CC',
				'iso_alpha3' => 'CCK',
				'iso_numeric' => '166',
				'currency_code' => 'AUD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'CC.png',
			),
			47 => 
			array (
				'id' => '50',
				'name' => 'Colombia',
				'iso_alpha2' => 'CO',
				'iso_alpha3' => 'COL',
				'iso_numeric' => '170',
				'currency_code' => 'COP',
				'currency_name' => 'Peso',
				'currrency_symbol' => '$',
				'flag' => 'CO.png',
			),
			48 => 
			array (
				'id' => '51',
				'name' => 'Comoros',
				'iso_alpha2' => 'KM',
				'iso_alpha3' => 'COM',
				'iso_numeric' => '174',
				'currency_code' => 'KMF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'KM.png',
			),
			49 => 
			array (
				'id' => '52',
				'name' => 'Cook Islands',
				'iso_alpha2' => 'CK',
				'iso_alpha3' => 'COK',
				'iso_numeric' => '184',
				'currency_code' => 'NZD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'CK.png',
			),
			50 => 
			array (
				'id' => '53',
				'name' => 'Costa Rica',
				'iso_alpha2' => 'CR',
				'iso_alpha3' => 'CRI',
				'iso_numeric' => '188',
				'currency_code' => 'CRC',
				'currency_name' => 'Colon',
				'currrency_symbol' => '₡',
				'flag' => 'CR.png',
			),
			51 => 
			array (
				'id' => '54',
				'name' => 'Croatia',
				'iso_alpha2' => 'HR',
				'iso_alpha3' => 'HRV',
				'iso_numeric' => '191',
				'currency_code' => 'HRK',
				'currency_name' => 'Kuna',
				'currrency_symbol' => 'kn',
				'flag' => 'HR.png',
			),
			52 => 
			array (
				'id' => '55',
				'name' => 'Cuba',
				'iso_alpha2' => 'CU',
				'iso_alpha3' => 'CUB',
				'iso_numeric' => '192',
				'currency_code' => 'CUP',
				'currency_name' => 'Peso',
				'currrency_symbol' => '₱',
				'flag' => 'CU.png',
			),
			53 => 
			array (
				'id' => '56',
				'name' => 'Cyprus',
				'iso_alpha2' => 'CY',
				'iso_alpha3' => 'CYP',
				'iso_numeric' => '196',
				'currency_code' => 'CYP',
				'currency_name' => 'Pound',
				'currrency_symbol' => NULL,
				'flag' => 'CY.png',
			),
			54 => 
			array (
				'id' => '57',
				'name' => 'Czech Republic',
				'iso_alpha2' => 'CZ',
				'iso_alpha3' => 'CZE',
				'iso_numeric' => '203',
				'currency_code' => 'CZK',
				'currency_name' => 'Koruna',
				'currrency_symbol' => 'Kč',
				'flag' => 'CZ.png',
			),
			55 => 
			array (
				'id' => '58',
				'name' => 'Democratic Republic of the Congo',
				'iso_alpha2' => 'CD',
				'iso_alpha3' => 'COD',
				'iso_numeric' => '180',
				'currency_code' => 'CDF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'CD.png',
			),
			56 => 
			array (
				'id' => '59',
				'name' => 'Denmark',
				'iso_alpha2' => 'DK',
				'iso_alpha3' => 'DNK',
				'iso_numeric' => '208',
				'currency_code' => 'DKK',
				'currency_name' => 'Krone',
				'currrency_symbol' => 'kr',
				'flag' => 'DK.png',
			),
			57 => 
			array (
				'id' => '60',
				'name' => 'Djibouti',
				'iso_alpha2' => 'DJ',
				'iso_alpha3' => 'DJI',
				'iso_numeric' => '262',
				'currency_code' => 'DJF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'DJ.png',
			),
			58 => 
			array (
				'id' => '61',
				'name' => 'Dominica',
				'iso_alpha2' => 'DM',
				'iso_alpha3' => 'DMA',
				'iso_numeric' => '212',
				'currency_code' => 'XCD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'DM.png',
			),
			59 => 
			array (
				'id' => '62',
				'name' => 'Dominican Republic',
				'iso_alpha2' => 'DO',
				'iso_alpha3' => 'DOM',
				'iso_numeric' => '214',
				'currency_code' => 'DOP',
				'currency_name' => 'Peso',
				'currrency_symbol' => 'RD$',
				'flag' => 'DO.png',
			),
			60 => 
			array (
				'id' => '63',
				'name' => 'East Timor',
				'iso_alpha2' => 'TL',
				'iso_alpha3' => 'TLS',
				'iso_numeric' => '626',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'TL.png',
			),
			61 => 
			array (
				'id' => '64',
				'name' => 'Ecuador',
				'iso_alpha2' => 'EC',
				'iso_alpha3' => 'ECU',
				'iso_numeric' => '218',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'EC.png',
			),
			62 => 
			array (
				'id' => '65',
				'name' => 'Egypt',
				'iso_alpha2' => 'EG',
				'iso_alpha3' => 'EGY',
				'iso_numeric' => '818',
				'currency_code' => 'EGP',
				'currency_name' => 'Pound',
				'currrency_symbol' => '£',
				'flag' => 'EG.png',
			),
			63 => 
			array (
				'id' => '66',
				'name' => 'El Salvador',
				'iso_alpha2' => 'SV',
				'iso_alpha3' => 'SLV',
				'iso_numeric' => '222',
				'currency_code' => 'SVC',
				'currency_name' => 'Colone',
				'currrency_symbol' => '$',
				'flag' => 'SV.png',
			),
			64 => 
			array (
				'id' => '67',
				'name' => 'Equatorial Guinea',
				'iso_alpha2' => 'GQ',
				'iso_alpha3' => 'GNQ',
				'iso_numeric' => '226',
				'currency_code' => 'XAF',
				'currency_name' => 'Franc',
				'currrency_symbol' => 'FCF',
				'flag' => 'GQ.png',
			),
			65 => 
			array (
				'id' => '68',
				'name' => 'Eritrea',
				'iso_alpha2' => 'ER',
				'iso_alpha3' => 'ERI',
				'iso_numeric' => '232',
				'currency_code' => 'ERN',
				'currency_name' => 'Nakfa',
				'currrency_symbol' => 'Nfk',
				'flag' => 'ER.png',
			),
			66 => 
			array (
				'id' => '69',
				'name' => 'Estonia',
				'iso_alpha2' => 'EE',
				'iso_alpha3' => 'EST',
				'iso_numeric' => '233',
				'currency_code' => 'EEK',
				'currency_name' => 'Kroon',
				'currrency_symbol' => 'kr',
				'flag' => 'EE.png',
			),
			67 => 
			array (
				'id' => '70',
				'name' => 'Ethiopia',
				'iso_alpha2' => 'ET',
				'iso_alpha3' => 'ETH',
				'iso_numeric' => '231',
				'currency_code' => 'ETB',
				'currency_name' => 'Birr',
				'currrency_symbol' => NULL,
				'flag' => 'ET.png',
			),
			68 => 
			array (
				'id' => '71',
				'name' => 'Falkland Islands',
				'iso_alpha2' => 'FK',
				'iso_alpha3' => 'FLK',
				'iso_numeric' => '238',
				'currency_code' => 'FKP',
				'currency_name' => 'Pound',
				'currrency_symbol' => '£',
				'flag' => 'FK.png',
			),
			69 => 
			array (
				'id' => '72',
				'name' => 'Faroe Islands',
				'iso_alpha2' => 'FO',
				'iso_alpha3' => 'FRO',
				'iso_numeric' => '234',
				'currency_code' => 'DKK',
				'currency_name' => 'Krone',
				'currrency_symbol' => 'kr',
				'flag' => 'FO.png',
			),
			70 => 
			array (
				'id' => '73',
				'name' => 'Fiji',
				'iso_alpha2' => 'FJ',
				'iso_alpha3' => 'FJI',
				'iso_numeric' => '242',
				'currency_code' => 'FJD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'FJ.png',
			),
			71 => 
			array (
				'id' => '74',
				'name' => 'Finland',
				'iso_alpha2' => 'FI',
				'iso_alpha3' => 'FIN',
				'iso_numeric' => '246',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'FI.png',
			),
			72 => 
			array (
				'id' => '75',
				'name' => 'France',
				'iso_alpha2' => 'FR',
				'iso_alpha3' => 'FRA',
				'iso_numeric' => '250',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'FR.png',
			),
			73 => 
			array (
				'id' => '76',
				'name' => 'French Guiana',
				'iso_alpha2' => 'GF',
				'iso_alpha3' => 'GUF',
				'iso_numeric' => '254',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'GF.png',
			),
			74 => 
			array (
				'id' => '77',
				'name' => 'French Polynesia',
				'iso_alpha2' => 'PF',
				'iso_alpha3' => 'PYF',
				'iso_numeric' => '258',
				'currency_code' => 'XPF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'PF.png',
			),
			75 => 
			array (
				'id' => '78',
				'name' => 'French Southern Territories',
				'iso_alpha2' => 'TF',
				'iso_alpha3' => 'ATF',
				'iso_numeric' => '260',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro  ',
				'currrency_symbol' => '€',
				'flag' => 'TF.png',
			),
			76 => 
			array (
				'id' => '79',
				'name' => 'Gabon',
				'iso_alpha2' => 'GA',
				'iso_alpha3' => 'GAB',
				'iso_numeric' => '266',
				'currency_code' => 'XAF',
				'currency_name' => 'Franc',
				'currrency_symbol' => 'FCF',
				'flag' => 'GA.png',
			),
			77 => 
			array (
				'id' => '80',
				'name' => 'Gambia',
				'iso_alpha2' => 'GM',
				'iso_alpha3' => 'GMB',
				'iso_numeric' => '270',
				'currency_code' => 'GMD',
				'currency_name' => 'Dalasi',
				'currrency_symbol' => 'D',
				'flag' => 'GM.png',
			),
			78 => 
			array (
				'id' => '81',
				'name' => 'Georgia',
				'iso_alpha2' => 'GE',
				'iso_alpha3' => 'GEO',
				'iso_numeric' => '268',
				'currency_code' => 'GEL',
				'currency_name' => 'Lari',
				'currrency_symbol' => NULL,
				'flag' => 'GE.png',
			),
			79 => 
			array (
				'id' => '82',
				'name' => 'Germany',
				'iso_alpha2' => 'DE',
				'iso_alpha3' => 'DEU',
				'iso_numeric' => '276',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'DE.png',
			),
			80 => 
			array (
				'id' => '83',
				'name' => 'Ghana',
				'iso_alpha2' => 'GH',
				'iso_alpha3' => 'GHA',
				'iso_numeric' => '288',
				'currency_code' => 'GHC',
				'currency_name' => 'Cedi',
				'currrency_symbol' => '¢',
				'flag' => 'GH.png',
			),
			81 => 
			array (
				'id' => '84',
				'name' => 'Gibraltar',
				'iso_alpha2' => 'GI',
				'iso_alpha3' => 'GIB',
				'iso_numeric' => '292',
				'currency_code' => 'GIP',
				'currency_name' => 'Pound',
				'currrency_symbol' => '£',
				'flag' => 'GI.png',
			),
			82 => 
			array (
				'id' => '85',
				'name' => 'Greece',
				'iso_alpha2' => 'GR',
				'iso_alpha3' => 'GRC',
				'iso_numeric' => '300',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'GR.png',
			),
			83 => 
			array (
				'id' => '86',
				'name' => 'Greenland',
				'iso_alpha2' => 'GL',
				'iso_alpha3' => 'GRL',
				'iso_numeric' => '304',
				'currency_code' => 'DKK',
				'currency_name' => 'Krone',
				'currrency_symbol' => 'kr',
				'flag' => 'GL.png',
			),
			84 => 
			array (
				'id' => '87',
				'name' => 'Grenada',
				'iso_alpha2' => 'GD',
				'iso_alpha3' => 'GRD',
				'iso_numeric' => '308',
				'currency_code' => 'XCD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'GD.png',
			),
			85 => 
			array (
				'id' => '88',
				'name' => 'Guadeloupe',
				'iso_alpha2' => 'GP',
				'iso_alpha3' => 'GLP',
				'iso_numeric' => '312',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'GP.png',
			),
			86 => 
			array (
				'id' => '89',
				'name' => 'Guam',
				'iso_alpha2' => 'GU',
				'iso_alpha3' => 'GUM',
				'iso_numeric' => '316',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'GU.png',
			),
			87 => 
			array (
				'id' => '90',
				'name' => 'Guatemala',
				'iso_alpha2' => 'GT',
				'iso_alpha3' => 'GTM',
				'iso_numeric' => '320',
				'currency_code' => 'GTQ',
				'currency_name' => 'Quetzal',
				'currrency_symbol' => 'Q',
				'flag' => 'GT.png',
			),
			88 => 
			array (
				'id' => '91',
				'name' => 'Guinea',
				'iso_alpha2' => 'GN',
				'iso_alpha3' => 'GIN',
				'iso_numeric' => '324',
				'currency_code' => 'GNF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'GN.png',
			),
			89 => 
			array (
				'id' => '92',
				'name' => 'Guinea-Bissau',
				'iso_alpha2' => 'GW',
				'iso_alpha3' => 'GNB',
				'iso_numeric' => '624',
				'currency_code' => 'XOF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'GW.png',
			),
			90 => 
			array (
				'id' => '93',
				'name' => 'Guyana',
				'iso_alpha2' => 'GY',
				'iso_alpha3' => 'GUY',
				'iso_numeric' => '328',
				'currency_code' => 'GYD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'GY.png',
			),
			91 => 
			array (
				'id' => '94',
				'name' => 'Haiti',
				'iso_alpha2' => 'HT',
				'iso_alpha3' => 'HTI',
				'iso_numeric' => '332',
				'currency_code' => 'HTG',
				'currency_name' => 'Gourde',
				'currrency_symbol' => 'G',
				'flag' => 'HT.png',
			),
			92 => 
			array (
				'id' => '95',
				'name' => 'Heard Island and McDonald Islands',
				'iso_alpha2' => 'HM',
				'iso_alpha3' => 'HMD',
				'iso_numeric' => '334',
				'currency_code' => 'AUD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'HM.png',
			),
			93 => 
			array (
				'id' => '96',
				'name' => 'Honduras',
				'iso_alpha2' => 'HN',
				'iso_alpha3' => 'HND',
				'iso_numeric' => '340',
				'currency_code' => 'HNL',
				'currency_name' => 'Lempira',
				'currrency_symbol' => 'L',
				'flag' => 'HN.png',
			),
			94 => 
			array (
				'id' => '97',
				'name' => 'Hong Kong',
				'iso_alpha2' => 'HK',
				'iso_alpha3' => 'HKG',
				'iso_numeric' => '344',
				'currency_code' => 'HKD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'HK.png',
			),
			95 => 
			array (
				'id' => '98',
				'name' => 'Hungary',
				'iso_alpha2' => 'HU',
				'iso_alpha3' => 'HUN',
				'iso_numeric' => '348',
				'currency_code' => 'HUF',
				'currency_name' => 'Forint',
				'currrency_symbol' => 'Ft',
				'flag' => 'HU.png',
			),
			96 => 
			array (
				'id' => '99',
				'name' => 'Iceland',
				'iso_alpha2' => 'IS',
				'iso_alpha3' => 'ISL',
				'iso_numeric' => '352',
				'currency_code' => 'ISK',
				'currency_name' => 'Krona',
				'currrency_symbol' => 'kr',
				'flag' => 'IS.png',
			),
			97 => 
			array (
				'id' => '100',
				'name' => 'India',
				'iso_alpha2' => 'IN',
				'iso_alpha3' => 'IND',
				'iso_numeric' => '356',
				'currency_code' => 'INR',
				'currency_name' => 'Rupee',
				'currrency_symbol' => '₹',
				'flag' => 'IN.png',
			),
			98 => 
			array (
				'id' => '101',
				'name' => 'Indonesia',
				'iso_alpha2' => 'ID',
				'iso_alpha3' => 'IDN',
				'iso_numeric' => '360',
				'currency_code' => 'IDR',
				'currency_name' => 'Rupiah',
				'currrency_symbol' => 'Rp',
				'flag' => 'ID.png',
			),
			99 => 
			array (
				'id' => '102',
				'name' => 'Iran',
				'iso_alpha2' => 'IR',
				'iso_alpha3' => 'IRN',
				'iso_numeric' => '364',
				'currency_code' => 'IRR',
				'currency_name' => 'Rial',
				'currrency_symbol' => '﷼',
				'flag' => 'IR.png',
			),
			100 => 
			array (
				'id' => '103',
				'name' => 'Iraq',
				'iso_alpha2' => 'IQ',
				'iso_alpha3' => 'IRQ',
				'iso_numeric' => '368',
				'currency_code' => 'IQD',
				'currency_name' => 'Dinar',
				'currrency_symbol' => NULL,
				'flag' => 'IQ.png',
			),
			101 => 
			array (
				'id' => '104',
				'name' => 'Ireland',
				'iso_alpha2' => 'IE',
				'iso_alpha3' => 'IRL',
				'iso_numeric' => '372',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'IE.png',
			),
			102 => 
			array (
				'id' => '105',
				'name' => 'Israel',
				'iso_alpha2' => 'IL',
				'iso_alpha3' => 'ISR',
				'iso_numeric' => '376',
				'currency_code' => 'ILS',
				'currency_name' => 'Shekel',
				'currrency_symbol' => '₪',
				'flag' => 'IL.png',
			),
			103 => 
			array (
				'id' => '106',
				'name' => 'Italy',
				'iso_alpha2' => 'IT',
				'iso_alpha3' => 'ITA',
				'iso_numeric' => '380',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'IT.png',
			),
			104 => 
			array (
				'id' => '107',
				'name' => 'Ivory Coast',
				'iso_alpha2' => 'CI',
				'iso_alpha3' => 'CIV',
				'iso_numeric' => '384',
				'currency_code' => 'XOF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'CI.png',
			),
			105 => 
			array (
				'id' => '108',
				'name' => 'Jamaica',
				'iso_alpha2' => 'JM',
				'iso_alpha3' => 'JAM',
				'iso_numeric' => '388',
				'currency_code' => 'JMD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'JM.png',
			),
			106 => 
			array (
				'id' => '109',
				'name' => 'Japan',
				'iso_alpha2' => 'JP',
				'iso_alpha3' => 'JPN',
				'iso_numeric' => '392',
				'currency_code' => 'JPY',
				'currency_name' => 'Yen',
				'currrency_symbol' => '¥',
				'flag' => 'JP.png',
			),
			107 => 
			array (
				'id' => '110',
				'name' => 'Jordan',
				'iso_alpha2' => 'JO',
				'iso_alpha3' => 'JOR',
				'iso_numeric' => '400',
				'currency_code' => 'JOD',
				'currency_name' => 'Dinar',
				'currrency_symbol' => NULL,
				'flag' => 'JO.png',
			),
			108 => 
			array (
				'id' => '111',
				'name' => 'Kazakhstan',
				'iso_alpha2' => 'KZ',
				'iso_alpha3' => 'KAZ',
				'iso_numeric' => '398',
				'currency_code' => 'KZT',
				'currency_name' => 'Tenge',
				'currrency_symbol' => 'лв',
				'flag' => 'KZ.png',
			),
			109 => 
			array (
				'id' => '112',
				'name' => 'Kenya',
				'iso_alpha2' => 'KE',
				'iso_alpha3' => 'KEN',
				'iso_numeric' => '404',
				'currency_code' => 'KES',
				'currency_name' => 'Shilling',
				'currrency_symbol' => NULL,
				'flag' => 'KE.png',
			),
			110 => 
			array (
				'id' => '113',
				'name' => 'Kiribati',
				'iso_alpha2' => 'KI',
				'iso_alpha3' => 'KIR',
				'iso_numeric' => '296',
				'currency_code' => 'AUD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'KI.png',
			),
			111 => 
			array (
				'id' => '114',
				'name' => 'Kuwait',
				'iso_alpha2' => 'KW',
				'iso_alpha3' => 'KWT',
				'iso_numeric' => '414',
				'currency_code' => 'KWD',
				'currency_name' => 'Dinar',
				'currrency_symbol' => NULL,
				'flag' => 'KW.png',
			),
			112 => 
			array (
				'id' => '115',
				'name' => 'Kyrgyzstan',
				'iso_alpha2' => 'KG',
				'iso_alpha3' => 'KGZ',
				'iso_numeric' => '417',
				'currency_code' => 'KGS',
				'currency_name' => 'Som',
				'currrency_symbol' => 'лв',
				'flag' => 'KG.png',
			),
			113 => 
			array (
				'id' => '116',
				'name' => 'Laos',
				'iso_alpha2' => 'LA',
				'iso_alpha3' => 'LAO',
				'iso_numeric' => '418',
				'currency_code' => 'LAK',
				'currency_name' => 'Kip',
				'currrency_symbol' => '₭',
				'flag' => 'LA.png',
			),
			114 => 
			array (
				'id' => '117',
				'name' => 'Latvia',
				'iso_alpha2' => 'LV',
				'iso_alpha3' => 'LVA',
				'iso_numeric' => '428',
				'currency_code' => 'LVL',
				'currency_name' => 'Lat',
				'currrency_symbol' => 'Ls',
				'flag' => 'LV.png',
			),
			115 => 
			array (
				'id' => '118',
				'name' => 'Lebanon',
				'iso_alpha2' => 'LB',
				'iso_alpha3' => 'LBN',
				'iso_numeric' => '422',
				'currency_code' => 'LBP',
				'currency_name' => 'Pound',
				'currrency_symbol' => '£',
				'flag' => 'LB.png',
			),
			116 => 
			array (
				'id' => '119',
				'name' => 'Lesotho',
				'iso_alpha2' => 'LS',
				'iso_alpha3' => 'LSO',
				'iso_numeric' => '426',
				'currency_code' => 'LSL',
				'currency_name' => 'Loti',
				'currrency_symbol' => 'L',
				'flag' => 'LS.png',
			),
			117 => 
			array (
				'id' => '120',
				'name' => 'Liberia',
				'iso_alpha2' => 'LR',
				'iso_alpha3' => 'LBR',
				'iso_numeric' => '430',
				'currency_code' => 'LRD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'LR.png',
			),
			118 => 
			array (
				'id' => '121',
				'name' => 'Libya',
				'iso_alpha2' => 'LY',
				'iso_alpha3' => 'LBY',
				'iso_numeric' => '434',
				'currency_code' => 'LYD',
				'currency_name' => 'Dinar',
				'currrency_symbol' => NULL,
				'flag' => 'LY.png',
			),
			119 => 
			array (
				'id' => '122',
				'name' => 'Liechtenstein',
				'iso_alpha2' => 'LI',
				'iso_alpha3' => 'LIE',
				'iso_numeric' => '438',
				'currency_code' => 'CHF',
				'currency_name' => 'Franc',
				'currrency_symbol' => 'CHF',
				'flag' => 'LI.png',
			),
			120 => 
			array (
				'id' => '123',
				'name' => 'Lithuania',
				'iso_alpha2' => 'LT',
				'iso_alpha3' => 'LTU',
				'iso_numeric' => '440',
				'currency_code' => 'LTL',
				'currency_name' => 'Litas',
				'currrency_symbol' => 'Lt',
				'flag' => 'LT.png',
			),
			121 => 
			array (
				'id' => '124',
				'name' => 'Luxembourg',
				'iso_alpha2' => 'LU',
				'iso_alpha3' => 'LUX',
				'iso_numeric' => '442',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'LU.png',
			),
			122 => 
			array (
				'id' => '125',
				'name' => 'Macao',
				'iso_alpha2' => 'MO',
				'iso_alpha3' => 'MAC',
				'iso_numeric' => '446',
				'currency_code' => 'MOP',
				'currency_name' => 'Pataca',
				'currrency_symbol' => 'MOP',
				'flag' => 'MO.png',
			),
			123 => 
			array (
				'id' => '126',
				'name' => 'Macedonia',
				'iso_alpha2' => 'MK',
				'iso_alpha3' => 'MKD',
				'iso_numeric' => '807',
				'currency_code' => 'MKD',
				'currency_name' => 'Denar',
				'currrency_symbol' => 'ден',
				'flag' => 'MK.png',
			),
			124 => 
			array (
				'id' => '127',
				'name' => 'Madagascar',
				'iso_alpha2' => 'MG',
				'iso_alpha3' => 'MDG',
				'iso_numeric' => '450',
				'currency_code' => 'MGA',
				'currency_name' => 'Ariary',
				'currrency_symbol' => NULL,
				'flag' => 'MG.png',
			),
			125 => 
			array (
				'id' => '128',
				'name' => 'Malawi',
				'iso_alpha2' => 'MW',
				'iso_alpha3' => 'MWI',
				'iso_numeric' => '454',
				'currency_code' => 'MWK',
				'currency_name' => 'Kwacha',
				'currrency_symbol' => 'MK',
				'flag' => 'MW.png',
			),
			126 => 
			array (
				'id' => '129',
				'name' => 'Malaysia',
				'iso_alpha2' => 'MY',
				'iso_alpha3' => 'MYS',
				'iso_numeric' => '458',
				'currency_code' => 'MYR',
				'currency_name' => 'Ringgit',
				'currrency_symbol' => 'RM',
				'flag' => 'MY.png',
			),
			127 => 
			array (
				'id' => '130',
				'name' => 'Maldives',
				'iso_alpha2' => 'MV',
				'iso_alpha3' => 'MDV',
				'iso_numeric' => '462',
				'currency_code' => 'MVR',
				'currency_name' => 'Rufiyaa',
				'currrency_symbol' => 'Rf',
				'flag' => 'MV.png',
			),
			128 => 
			array (
				'id' => '131',
				'name' => 'Mali',
				'iso_alpha2' => 'ML',
				'iso_alpha3' => 'MLI',
				'iso_numeric' => '466',
				'currency_code' => 'XOF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'ML.png',
			),
			129 => 
			array (
				'id' => '132',
				'name' => 'Malta',
				'iso_alpha2' => 'MT',
				'iso_alpha3' => 'MLT',
				'iso_numeric' => '470',
				'currency_code' => 'MTL',
				'currency_name' => 'Lira',
				'currrency_symbol' => NULL,
				'flag' => 'MT.png',
			),
			130 => 
			array (
				'id' => '133',
				'name' => 'Marshall Islands',
				'iso_alpha2' => 'MH',
				'iso_alpha3' => 'MHL',
				'iso_numeric' => '584',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'MH.png',
			),
			131 => 
			array (
				'id' => '134',
				'name' => 'Martinique',
				'iso_alpha2' => 'MQ',
				'iso_alpha3' => 'MTQ',
				'iso_numeric' => '474',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'MQ.png',
			),
			132 => 
			array (
				'id' => '135',
				'name' => 'Mauritania',
				'iso_alpha2' => 'MR',
				'iso_alpha3' => 'MRT',
				'iso_numeric' => '478',
				'currency_code' => 'MRO',
				'currency_name' => 'Ouguiya',
				'currrency_symbol' => 'UM',
				'flag' => 'MR.png',
			),
			133 => 
			array (
				'id' => '136',
				'name' => 'Mauritius',
				'iso_alpha2' => 'MU',
				'iso_alpha3' => 'MUS',
				'iso_numeric' => '480',
				'currency_code' => 'MUR',
				'currency_name' => 'Rupee',
				'currrency_symbol' => '₨',
				'flag' => 'MU.png',
			),
			134 => 
			array (
				'id' => '137',
				'name' => 'Mayotte',
				'iso_alpha2' => 'YT',
				'iso_alpha3' => 'MYT',
				'iso_numeric' => '175',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'YT.png',
			),
			135 => 
			array (
				'id' => '138',
				'name' => 'Mexico',
				'iso_alpha2' => 'MX',
				'iso_alpha3' => 'MEX',
				'iso_numeric' => '484',
				'currency_code' => 'MXN',
				'currency_name' => 'Peso',
				'currrency_symbol' => '$',
				'flag' => 'MX.png',
			),
			136 => 
			array (
				'id' => '139',
				'name' => 'Micronesia',
				'iso_alpha2' => 'FM',
				'iso_alpha3' => 'FSM',
				'iso_numeric' => '583',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'FM.png',
			),
			137 => 
			array (
				'id' => '140',
				'name' => 'Moldova',
				'iso_alpha2' => 'MD',
				'iso_alpha3' => 'MDA',
				'iso_numeric' => '498',
				'currency_code' => 'MDL',
				'currency_name' => 'Leu',
				'currrency_symbol' => NULL,
				'flag' => 'MD.png',
			),
			138 => 
			array (
				'id' => '141',
				'name' => 'Monaco',
				'iso_alpha2' => 'MC',
				'iso_alpha3' => 'MCO',
				'iso_numeric' => '492',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'MC.png',
			),
			139 => 
			array (
				'id' => '142',
				'name' => 'Mongolia',
				'iso_alpha2' => 'MN',
				'iso_alpha3' => 'MNG',
				'iso_numeric' => '496',
				'currency_code' => 'MNT',
				'currency_name' => 'Tugrik',
				'currrency_symbol' => '₮',
				'flag' => 'MN.png',
			),
			140 => 
			array (
				'id' => '143',
				'name' => 'Montserrat',
				'iso_alpha2' => 'MS',
				'iso_alpha3' => 'MSR',
				'iso_numeric' => '500',
				'currency_code' => 'XCD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'MS.png',
			),
			141 => 
			array (
				'id' => '144',
				'name' => 'Morocco',
				'iso_alpha2' => 'MA',
				'iso_alpha3' => 'MAR',
				'iso_numeric' => '504',
				'currency_code' => 'MAD',
				'currency_name' => 'Dirham',
				'currrency_symbol' => NULL,
				'flag' => 'MA.png',
			),
			142 => 
			array (
				'id' => '145',
				'name' => 'Mozambique',
				'iso_alpha2' => 'MZ',
				'iso_alpha3' => 'MOZ',
				'iso_numeric' => '508',
				'currency_code' => 'MZN',
				'currency_name' => 'Meticail',
				'currrency_symbol' => 'MT',
				'flag' => 'MZ.png',
			),
			143 => 
			array (
				'id' => '146',
				'name' => 'Myanmar',
				'iso_alpha2' => 'MM',
				'iso_alpha3' => 'MMR',
				'iso_numeric' => '104',
				'currency_code' => 'MMK',
				'currency_name' => 'Kyat',
				'currrency_symbol' => 'K',
				'flag' => 'MM.png',
			),
			144 => 
			array (
				'id' => '147',
				'name' => 'Namibia',
				'iso_alpha2' => 'NA',
				'iso_alpha3' => 'NAM',
				'iso_numeric' => '516',
				'currency_code' => 'NAD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'NA.png',
			),
			145 => 
			array (
				'id' => '148',
				'name' => 'Nauru',
				'iso_alpha2' => 'NR',
				'iso_alpha3' => 'NRU',
				'iso_numeric' => '520',
				'currency_code' => 'AUD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'NR.png',
			),
			146 => 
			array (
				'id' => '149',
				'name' => 'Nepal',
				'iso_alpha2' => 'NP',
				'iso_alpha3' => 'NPL',
				'iso_numeric' => '524',
				'currency_code' => 'NPR',
				'currency_name' => 'Rupee',
				'currrency_symbol' => '₨',
				'flag' => 'NP.png',
			),
			147 => 
			array (
				'id' => '150',
				'name' => 'Netherlands',
				'iso_alpha2' => 'NL',
				'iso_alpha3' => 'NLD',
				'iso_numeric' => '528',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'NL.png',
			),
			148 => 
			array (
				'id' => '151',
				'name' => 'Netherlands Antilles',
				'iso_alpha2' => 'AN',
				'iso_alpha3' => 'ANT',
				'iso_numeric' => '530',
				'currency_code' => 'ANG',
				'currency_name' => 'Guilder',
				'currrency_symbol' => 'ƒ',
				'flag' => 'AN.png',
			),
			149 => 
			array (
				'id' => '152',
				'name' => 'New Caledonia',
				'iso_alpha2' => 'NC',
				'iso_alpha3' => 'NCL',
				'iso_numeric' => '540',
				'currency_code' => 'XPF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'NC.png',
			),
			150 => 
			array (
				'id' => '153',
				'name' => 'New Zealand',
				'iso_alpha2' => 'NZ',
				'iso_alpha3' => 'NZL',
				'iso_numeric' => '554',
				'currency_code' => 'NZD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'NZ.png',
			),
			151 => 
			array (
				'id' => '154',
				'name' => 'Nicaragua',
				'iso_alpha2' => 'NI',
				'iso_alpha3' => 'NIC',
				'iso_numeric' => '558',
				'currency_code' => 'NIO',
				'currency_name' => 'Cordoba',
				'currrency_symbol' => 'C$',
				'flag' => 'NI.png',
			),
			152 => 
			array (
				'id' => '155',
				'name' => 'Niger',
				'iso_alpha2' => 'NE',
				'iso_alpha3' => 'NER',
				'iso_numeric' => '562',
				'currency_code' => 'XOF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'NE.png',
			),
			153 => 
			array (
				'id' => '156',
				'name' => 'Nigeria',
				'iso_alpha2' => 'NG',
				'iso_alpha3' => 'NGA',
				'iso_numeric' => '566',
				'currency_code' => 'NGN',
				'currency_name' => 'Naira',
				'currrency_symbol' => '₦',
				'flag' => 'NG.png',
			),
			154 => 
			array (
				'id' => '157',
				'name' => 'Niue',
				'iso_alpha2' => 'NU',
				'iso_alpha3' => 'NIU',
				'iso_numeric' => '570',
				'currency_code' => 'NZD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'NU.png',
			),
			155 => 
			array (
				'id' => '158',
				'name' => 'Norfolk Island',
				'iso_alpha2' => 'NF',
				'iso_alpha3' => 'NFK',
				'iso_numeric' => '574',
				'currency_code' => 'AUD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'NF.png',
			),
			156 => 
			array (
				'id' => '159',
				'name' => 'North Korea',
				'iso_alpha2' => 'KP',
				'iso_alpha3' => 'PRK',
				'iso_numeric' => '408',
				'currency_code' => 'KPW',
				'currency_name' => 'Won',
				'currrency_symbol' => '₩',
				'flag' => 'KP.png',
			),
			157 => 
			array (
				'id' => '160',
				'name' => 'Northern Mariana Islands',
				'iso_alpha2' => 'MP',
				'iso_alpha3' => 'MNP',
				'iso_numeric' => '580',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'MP.png',
			),
			158 => 
			array (
				'id' => '161',
				'name' => 'Norway',
				'iso_alpha2' => 'NO',
				'iso_alpha3' => 'NOR',
				'iso_numeric' => '578',
				'currency_code' => 'NOK',
				'currency_name' => 'Krone',
				'currrency_symbol' => 'kr',
				'flag' => 'NO.png',
			),
			159 => 
			array (
				'id' => '162',
				'name' => 'Oman',
				'iso_alpha2' => 'OM',
				'iso_alpha3' => 'OMN',
				'iso_numeric' => '512',
				'currency_code' => 'OMR',
				'currency_name' => 'Rial',
				'currrency_symbol' => '﷼',
				'flag' => 'OM.png',
			),
			160 => 
			array (
				'id' => '163',
				'name' => 'Pakistan',
				'iso_alpha2' => 'PK',
				'iso_alpha3' => 'PAK',
				'iso_numeric' => '586',
				'currency_code' => 'PKR',
				'currency_name' => 'Rupee',
				'currrency_symbol' => '₨',
				'flag' => 'PK.png',
			),
			161 => 
			array (
				'id' => '164',
				'name' => 'Palau',
				'iso_alpha2' => 'PW',
				'iso_alpha3' => 'PLW',
				'iso_numeric' => '585',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'PW.png',
			),
			162 => 
			array (
				'id' => '165',
				'name' => 'Palestinian Territory',
				'iso_alpha2' => 'PS',
				'iso_alpha3' => 'PSE',
				'iso_numeric' => '275',
				'currency_code' => 'ILS',
				'currency_name' => 'Shekel',
				'currrency_symbol' => '₪',
				'flag' => 'PS.png',
			),
			163 => 
			array (
				'id' => '166',
				'name' => 'Panama',
				'iso_alpha2' => 'PA',
				'iso_alpha3' => 'PAN',
				'iso_numeric' => '591',
				'currency_code' => 'PAB',
				'currency_name' => 'Balboa',
				'currrency_symbol' => 'B/.',
				'flag' => 'PA.png',
			),
			164 => 
			array (
				'id' => '167',
				'name' => 'Papua New Guinea',
				'iso_alpha2' => 'PG',
				'iso_alpha3' => 'PNG',
				'iso_numeric' => '598',
				'currency_code' => 'PGK',
				'currency_name' => 'Kina',
				'currrency_symbol' => NULL,
				'flag' => 'PG.png',
			),
			165 => 
			array (
				'id' => '168',
				'name' => 'Paraguay',
				'iso_alpha2' => 'PY',
				'iso_alpha3' => 'PRY',
				'iso_numeric' => '600',
				'currency_code' => 'PYG',
				'currency_name' => 'Guarani',
				'currrency_symbol' => 'Gs',
				'flag' => 'PY.png',
			),
			166 => 
			array (
				'id' => '169',
				'name' => 'Peru',
				'iso_alpha2' => 'PE',
				'iso_alpha3' => 'PER',
				'iso_numeric' => '604',
				'currency_code' => 'PEN',
				'currency_name' => 'Sol',
				'currrency_symbol' => 'S/.',
				'flag' => 'PE.png',
			),
			167 => 
			array (
				'id' => '170',
				'name' => 'Philippines',
				'iso_alpha2' => 'PH',
				'iso_alpha3' => 'PHL',
				'iso_numeric' => '608',
				'currency_code' => 'PHP',
				'currency_name' => 'Peso',
				'currrency_symbol' => 'Php',
				'flag' => 'PH.png',
			),
			168 => 
			array (
				'id' => '171',
				'name' => 'Pitcairn',
				'iso_alpha2' => 'PN',
				'iso_alpha3' => 'PCN',
				'iso_numeric' => '612',
				'currency_code' => 'NZD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'PN.png',
			),
			169 => 
			array (
				'id' => '172',
				'name' => 'Poland',
				'iso_alpha2' => 'PL',
				'iso_alpha3' => 'POL',
				'iso_numeric' => '616',
				'currency_code' => 'PLN',
				'currency_name' => 'Zloty',
				'currrency_symbol' => 'zł',
				'flag' => 'PL.png',
			),
			170 => 
			array (
				'id' => '173',
				'name' => 'Portugal',
				'iso_alpha2' => 'PT',
				'iso_alpha3' => 'PRT',
				'iso_numeric' => '620',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'PT.png',
			),
			171 => 
			array (
				'id' => '174',
				'name' => 'Puerto Rico',
				'iso_alpha2' => 'PR',
				'iso_alpha3' => 'PRI',
				'iso_numeric' => '630',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'PR.png',
			),
			172 => 
			array (
				'id' => '175',
				'name' => 'Qatar',
				'iso_alpha2' => 'QA',
				'iso_alpha3' => 'QAT',
				'iso_numeric' => '634',
				'currency_code' => 'QAR',
				'currency_name' => 'Rial',
				'currrency_symbol' => '﷼',
				'flag' => 'QA.png',
			),
			173 => 
			array (
				'id' => '176',
				'name' => 'Republic of the Congo',
				'iso_alpha2' => 'CG',
				'iso_alpha3' => 'COG',
				'iso_numeric' => '178',
				'currency_code' => 'XAF',
				'currency_name' => 'Franc',
				'currrency_symbol' => 'FCF',
				'flag' => 'CG.png',
			),
			174 => 
			array (
				'id' => '177',
				'name' => 'Reunion',
				'iso_alpha2' => 'RE',
				'iso_alpha3' => 'REU',
				'iso_numeric' => '638',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'RE.png',
			),
			175 => 
			array (
				'id' => '178',
				'name' => 'Romania',
				'iso_alpha2' => 'RO',
				'iso_alpha3' => 'ROU',
				'iso_numeric' => '642',
				'currency_code' => 'RON',
				'currency_name' => 'Leu',
				'currrency_symbol' => 'lei',
				'flag' => 'RO.png',
			),
			176 => 
			array (
				'id' => '179',
				'name' => 'Russia',
				'iso_alpha2' => 'RU',
				'iso_alpha3' => 'RUS',
				'iso_numeric' => '643',
				'currency_code' => 'RUB',
				'currency_name' => 'Ruble',
				'currrency_symbol' => 'руб',
				'flag' => 'RU.png',
			),
			177 => 
			array (
				'id' => '180',
				'name' => 'Rwanda',
				'iso_alpha2' => 'RW',
				'iso_alpha3' => 'RWA',
				'iso_numeric' => '646',
				'currency_code' => 'RWF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'RW.png',
			),
			178 => 
			array (
				'id' => '181',
				'name' => 'Saint Helena',
				'iso_alpha2' => 'SH',
				'iso_alpha3' => 'SHN',
				'iso_numeric' => '654',
				'currency_code' => 'SHP',
				'currency_name' => 'Pound',
				'currrency_symbol' => '£',
				'flag' => 'SH.png',
			),
			179 => 
			array (
				'id' => '182',
				'name' => 'Saint Kitts and Nevis',
				'iso_alpha2' => 'KN',
				'iso_alpha3' => 'KNA',
				'iso_numeric' => '659',
				'currency_code' => 'XCD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'KN.png',
			),
			180 => 
			array (
				'id' => '183',
				'name' => 'Saint Lucia',
				'iso_alpha2' => 'LC',
				'iso_alpha3' => 'LCA',
				'iso_numeric' => '662',
				'currency_code' => 'XCD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'LC.png',
			),
			181 => 
			array (
				'id' => '184',
				'name' => 'Saint Pierre and Miquelon',
				'iso_alpha2' => 'PM',
				'iso_alpha3' => 'SPM',
				'iso_numeric' => '666',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'PM.png',
			),
			182 => 
			array (
				'id' => '185',
				'name' => 'Saint Vincent and the Grenadines',
				'iso_alpha2' => 'VC',
				'iso_alpha3' => 'VCT',
				'iso_numeric' => '670',
				'currency_code' => 'XCD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'VC.png',
			),
			183 => 
			array (
				'id' => '186',
				'name' => 'Samoa',
				'iso_alpha2' => 'WS',
				'iso_alpha3' => 'WSM',
				'iso_numeric' => '882',
				'currency_code' => 'WST',
				'currency_name' => 'Tala',
				'currrency_symbol' => 'WS$',
				'flag' => 'WS.png',
			),
			184 => 
			array (
				'id' => '187',
				'name' => 'San Marino',
				'iso_alpha2' => 'SM',
				'iso_alpha3' => 'SMR',
				'iso_numeric' => '674',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'SM.png',
			),
			185 => 
			array (
				'id' => '188',
				'name' => 'Sao Tome and Principe',
				'iso_alpha2' => 'ST',
				'iso_alpha3' => 'STP',
				'iso_numeric' => '678',
				'currency_code' => 'STD',
				'currency_name' => 'Dobra',
				'currrency_symbol' => 'Db',
				'flag' => 'ST.png',
			),
			186 => 
			array (
				'id' => '189',
				'name' => 'Saudi Arabia',
				'iso_alpha2' => 'SA',
				'iso_alpha3' => 'SAU',
				'iso_numeric' => '682',
				'currency_code' => 'SAR',
				'currency_name' => 'Rial',
				'currrency_symbol' => '﷼',
				'flag' => 'SA.png',
			),
			187 => 
			array (
				'id' => '190',
				'name' => 'Senegal',
				'iso_alpha2' => 'SN',
				'iso_alpha3' => 'SEN',
				'iso_numeric' => '686',
				'currency_code' => 'XOF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'SN.png',
			),
			188 => 
			array (
				'id' => '191',
				'name' => 'Serbia and Montenegro',
				'iso_alpha2' => 'CS',
				'iso_alpha3' => 'SCG',
				'iso_numeric' => '891',
				'currency_code' => 'RSD',
				'currency_name' => 'Dinar',
				'currrency_symbol' => 'Дин',
				'flag' => 'CS.png',
			),
			189 => 
			array (
				'id' => '192',
				'name' => 'Seychelles',
				'iso_alpha2' => 'SC',
				'iso_alpha3' => 'SYC',
				'iso_numeric' => '690',
				'currency_code' => 'SCR',
				'currency_name' => 'Rupee',
				'currrency_symbol' => '₨',
				'flag' => 'SC.png',
			),
			190 => 
			array (
				'id' => '193',
				'name' => 'Sierra Leone',
				'iso_alpha2' => 'SL',
				'iso_alpha3' => 'SLE',
				'iso_numeric' => '694',
				'currency_code' => 'SLL',
				'currency_name' => 'Leone',
				'currrency_symbol' => 'Le',
				'flag' => 'SL.png',
			),
			191 => 
			array (
				'id' => '194',
				'name' => 'Singapore',
				'iso_alpha2' => 'SG',
				'iso_alpha3' => 'SGP',
				'iso_numeric' => '702',
				'currency_code' => 'SGD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'SG.png',
			),
			192 => 
			array (
				'id' => '195',
				'name' => 'Slovakia',
				'iso_alpha2' => 'SK',
				'iso_alpha3' => 'SVK',
				'iso_numeric' => '703',
				'currency_code' => 'SKK',
				'currency_name' => 'Koruna',
				'currrency_symbol' => 'Sk',
				'flag' => 'SK.png',
			),
			193 => 
			array (
				'id' => '196',
				'name' => 'Slovenia',
				'iso_alpha2' => 'SI',
				'iso_alpha3' => 'SVN',
				'iso_numeric' => '705',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'SI.png',
			),
			194 => 
			array (
				'id' => '197',
				'name' => 'Solomon Islands',
				'iso_alpha2' => 'SB',
				'iso_alpha3' => 'SLB',
				'iso_numeric' => '90',
				'currency_code' => 'SBD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'SB.png',
			),
			195 => 
			array (
				'id' => '198',
				'name' => 'Somalia',
				'iso_alpha2' => 'SO',
				'iso_alpha3' => 'SOM',
				'iso_numeric' => '706',
				'currency_code' => 'SOS',
				'currency_name' => 'Shilling',
				'currrency_symbol' => 'S',
				'flag' => 'SO.png',
			),
			196 => 
			array (
				'id' => '199',
				'name' => 'South Africa',
				'iso_alpha2' => 'ZA',
				'iso_alpha3' => 'ZAF',
				'iso_numeric' => '710',
				'currency_code' => 'ZAR',
				'currency_name' => 'Rand',
				'currrency_symbol' => 'R',
				'flag' => 'ZA.png',
			),
			197 => 
			array (
				'id' => '200',
				'name' => 'South Georgia and the South Sandwich Islands',
				'iso_alpha2' => 'GS',
				'iso_alpha3' => 'SGS',
				'iso_numeric' => '239',
				'currency_code' => 'GBP',
				'currency_name' => 'Pound',
				'currrency_symbol' => '£',
				'flag' => 'GS.png',
			),
			198 => 
			array (
				'id' => '201',
				'name' => 'South Korea',
				'iso_alpha2' => 'KR',
				'iso_alpha3' => 'KOR',
				'iso_numeric' => '410',
				'currency_code' => 'KRW',
				'currency_name' => 'Won',
				'currrency_symbol' => '₩',
				'flag' => 'KR.png',
			),
			199 => 
			array (
				'id' => '202',
				'name' => 'Spain',
				'iso_alpha2' => 'ES',
				'iso_alpha3' => 'ESP',
				'iso_numeric' => '724',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'ES.png',
			),
			200 => 
			array (
				'id' => '203',
				'name' => 'Sri Lanka',
				'iso_alpha2' => 'LK',
				'iso_alpha3' => 'LKA',
				'iso_numeric' => '144',
				'currency_code' => 'LKR',
				'currency_name' => 'Rupee',
				'currrency_symbol' => '₨',
				'flag' => 'LK.png',
			),
			201 => 
			array (
				'id' => '204',
				'name' => 'Sudan',
				'iso_alpha2' => 'SD',
				'iso_alpha3' => 'SDN',
				'iso_numeric' => '736',
				'currency_code' => 'SDD',
				'currency_name' => 'Dinar',
				'currrency_symbol' => NULL,
				'flag' => 'SD.png',
			),
			202 => 
			array (
				'id' => '205',
				'name' => 'Suriname',
				'iso_alpha2' => 'SR',
				'iso_alpha3' => 'SUR',
				'iso_numeric' => '740',
				'currency_code' => 'SRD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'SR.png',
			),
			203 => 
			array (
				'id' => '206',
				'name' => 'Svalbard and Jan Mayen',
				'iso_alpha2' => 'SJ',
				'iso_alpha3' => 'SJM',
				'iso_numeric' => '744',
				'currency_code' => 'NOK',
				'currency_name' => 'Krone',
				'currrency_symbol' => 'kr',
				'flag' => 'SJ.png',
			),
			204 => 
			array (
				'id' => '207',
				'name' => 'Swaziland',
				'iso_alpha2' => 'SZ',
				'iso_alpha3' => 'SWZ',
				'iso_numeric' => '748',
				'currency_code' => 'SZL',
				'currency_name' => 'Lilangeni',
				'currrency_symbol' => NULL,
				'flag' => 'SZ.png',
			),
			205 => 
			array (
				'id' => '208',
				'name' => 'Sweden',
				'iso_alpha2' => 'SE',
				'iso_alpha3' => 'SWE',
				'iso_numeric' => '752',
				'currency_code' => 'SEK',
				'currency_name' => 'Krona',
				'currrency_symbol' => 'kr',
				'flag' => 'SE.png',
			),
			206 => 
			array (
				'id' => '209',
				'name' => 'Switzerland',
				'iso_alpha2' => 'CH',
				'iso_alpha3' => 'CHE',
				'iso_numeric' => '756',
				'currency_code' => 'CHF',
				'currency_name' => 'Franc',
				'currrency_symbol' => 'CHF',
				'flag' => 'CH.png',
			),
			207 => 
			array (
				'id' => '210',
				'name' => 'Syria',
				'iso_alpha2' => 'SY',
				'iso_alpha3' => 'SYR',
				'iso_numeric' => '760',
				'currency_code' => 'SYP',
				'currency_name' => 'Pound',
				'currrency_symbol' => '£',
				'flag' => 'SY.png',
			),
			208 => 
			array (
				'id' => '211',
				'name' => 'Taiwan',
				'iso_alpha2' => 'TW',
				'iso_alpha3' => 'TWN',
				'iso_numeric' => '158',
				'currency_code' => 'TWD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => 'NT$',
				'flag' => 'TW.png',
			),
			209 => 
			array (
				'id' => '212',
				'name' => 'Tajikistan',
				'iso_alpha2' => 'TJ',
				'iso_alpha3' => 'TJK',
				'iso_numeric' => '762',
				'currency_code' => 'TJS',
				'currency_name' => 'Somoni',
				'currrency_symbol' => NULL,
				'flag' => 'TJ.png',
			),
			210 => 
			array (
				'id' => '213',
				'name' => 'Tanzania',
				'iso_alpha2' => 'TZ',
				'iso_alpha3' => 'TZA',
				'iso_numeric' => '834',
				'currency_code' => 'TZS',
				'currency_name' => 'Shilling',
				'currrency_symbol' => NULL,
				'flag' => 'TZ.png',
			),
			211 => 
			array (
				'id' => '214',
				'name' => 'Thailand',
				'iso_alpha2' => 'TH',
				'iso_alpha3' => 'THA',
				'iso_numeric' => '764',
				'currency_code' => 'THB',
				'currency_name' => 'Baht',
				'currrency_symbol' => '฿',
				'flag' => 'TH.png',
			),
			212 => 
			array (
				'id' => '215',
				'name' => 'Togo',
				'iso_alpha2' => 'TG',
				'iso_alpha3' => 'TGO',
				'iso_numeric' => '768',
				'currency_code' => 'XOF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'TG.png',
			),
			213 => 
			array (
				'id' => '216',
				'name' => 'Tokelau',
				'iso_alpha2' => 'TK',
				'iso_alpha3' => 'TKL',
				'iso_numeric' => '772',
				'currency_code' => 'NZD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'TK.png',
			),
			214 => 
			array (
				'id' => '217',
				'name' => 'Tonga',
				'iso_alpha2' => 'TO',
				'iso_alpha3' => 'TON',
				'iso_numeric' => '776',
				'currency_code' => 'TOP',
				'currency_name' => 'Pa\'anga',
				'currrency_symbol' => 'T$',
				'flag' => 'TO.png',
			),
			215 => 
			array (
				'id' => '218',
				'name' => 'Trinidad and Tobago',
				'iso_alpha2' => 'TT',
				'iso_alpha3' => 'TTO',
				'iso_numeric' => '780',
				'currency_code' => 'TTD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => 'TT$',
				'flag' => 'TT.png',
			),
			216 => 
			array (
				'id' => '219',
				'name' => 'Tunisia',
				'iso_alpha2' => 'TN',
				'iso_alpha3' => 'TUN',
				'iso_numeric' => '788',
				'currency_code' => 'TND',
				'currency_name' => 'Dinar',
				'currrency_symbol' => NULL,
				'flag' => 'TN.png',
			),
			217 => 
			array (
				'id' => '220',
				'name' => 'Turkey',
				'iso_alpha2' => 'TR',
				'iso_alpha3' => 'TUR',
				'iso_numeric' => '792',
				'currency_code' => 'TRY',
				'currency_name' => 'Lira',
				'currrency_symbol' => 'YTL',
				'flag' => 'TR.png',
			),
			218 => 
			array (
				'id' => '221',
				'name' => 'Turkmenistan',
				'iso_alpha2' => 'TM',
				'iso_alpha3' => 'TKM',
				'iso_numeric' => '795',
				'currency_code' => 'TMM',
				'currency_name' => 'Manat',
				'currrency_symbol' => 'm',
				'flag' => 'TM.png',
			),
			219 => 
			array (
				'id' => '222',
				'name' => 'Turks and Caicos Islands',
				'iso_alpha2' => 'TC',
				'iso_alpha3' => 'TCA',
				'iso_numeric' => '796',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'TC.png',
			),
			220 => 
			array (
				'id' => '223',
				'name' => 'Tuvalu',
				'iso_alpha2' => 'TV',
				'iso_alpha3' => 'TUV',
				'iso_numeric' => '798',
				'currency_code' => 'AUD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'TV.png',
			),
			221 => 
			array (
				'id' => '224',
				'name' => 'U.S. Virgin Islands',
				'iso_alpha2' => 'VI',
				'iso_alpha3' => 'VIR',
				'iso_numeric' => '850',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'VI.png',
			),
			222 => 
			array (
				'id' => '225',
				'name' => 'Uganda',
				'iso_alpha2' => 'UG',
				'iso_alpha3' => 'UGA',
				'iso_numeric' => '800',
				'currency_code' => 'UGX',
				'currency_name' => 'Shilling',
				'currrency_symbol' => NULL,
				'flag' => 'UG.png',
			),
			223 => 
			array (
				'id' => '226',
				'name' => 'Ukraine',
				'iso_alpha2' => 'UA',
				'iso_alpha3' => 'UKR',
				'iso_numeric' => '804',
				'currency_code' => 'UAH',
				'currency_name' => 'Hryvnia',
				'currrency_symbol' => '₴',
				'flag' => 'UA.png',
			),
			224 => 
			array (
				'id' => '227',
				'name' => 'United Arab Emirates',
				'iso_alpha2' => 'AE',
				'iso_alpha3' => 'ARE',
				'iso_numeric' => '784',
				'currency_code' => 'AED',
				'currency_name' => 'Dirham',
				'currrency_symbol' => NULL,
				'flag' => 'AE.png',
			),
			225 => 
			array (
				'id' => '2',
				'name' => 'United Kingdom',
				'iso_alpha2' => 'GB',
				'iso_alpha3' => 'GBR',
				'iso_numeric' => '826',
				'currency_code' => 'GBP',
				'currency_name' => 'Pound',
				'currrency_symbol' => '£',
				'flag' => 'GB.png',
			),
			226 => 
			array (
				'id' => '1',
				'name' => 'United States',
				'iso_alpha2' => 'US',
				'iso_alpha3' => 'USA',
				'iso_numeric' => '840',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => '$',
				'flag' => 'US.png',
			),
			227 => 
			array (
				'id' => '228',
				'name' => 'United States Minor Outlying Islands',
				'iso_alpha2' => 'UM',
				'iso_alpha3' => 'UMI',
				'iso_numeric' => '581',
				'currency_code' => 'USD',
				'currency_name' => 'Dollar ',
				'currrency_symbol' => '$',
				'flag' => 'UM.png',
			),
			228 => 
			array (
				'id' => '229',
				'name' => 'Uruguay',
				'iso_alpha2' => 'UY',
				'iso_alpha3' => 'URY',
				'iso_numeric' => '858',
				'currency_code' => 'UYU',
				'currency_name' => 'Peso',
				'currrency_symbol' => '$U',
				'flag' => 'UY.png',
			),
			229 => 
			array (
				'id' => '230',
				'name' => 'Uzbekistan',
				'iso_alpha2' => 'UZ',
				'iso_alpha3' => 'UZB',
				'iso_numeric' => '860',
				'currency_code' => 'UZS',
				'currency_name' => 'Som',
				'currrency_symbol' => 'лв',
				'flag' => 'UZ.png',
			),
			230 => 
			array (
				'id' => '231',
				'name' => 'Vanuatu',
				'iso_alpha2' => 'VU',
				'iso_alpha3' => 'VUT',
				'iso_numeric' => '548',
				'currency_code' => 'VUV',
				'currency_name' => 'Vatu',
				'currrency_symbol' => 'Vt',
				'flag' => 'VU.png',
			),
			231 => 
			array (
				'id' => '232',
				'name' => 'Vatican',
				'iso_alpha2' => 'VA',
				'iso_alpha3' => 'VAT',
				'iso_numeric' => '336',
				'currency_code' => 'EUR',
				'currency_name' => 'Euro',
				'currrency_symbol' => '€',
				'flag' => 'VA.png',
			),
			232 => 
			array (
				'id' => '233',
				'name' => 'Venezuela',
				'iso_alpha2' => 'VE',
				'iso_alpha3' => 'VEN',
				'iso_numeric' => '862',
				'currency_code' => 'VEF',
				'currency_name' => 'Bolivar',
				'currrency_symbol' => 'Bs',
				'flag' => 'VE.png',
			),
			233 => 
			array (
				'id' => '234',
				'name' => 'Vietnam',
				'iso_alpha2' => 'VN',
				'iso_alpha3' => 'VNM',
				'iso_numeric' => '704',
				'currency_code' => 'VND',
				'currency_name' => 'Dong',
				'currrency_symbol' => '₫',
				'flag' => 'VN.png',
			),
			234 => 
			array (
				'id' => '235',
				'name' => 'Wallis and Futuna',
				'iso_alpha2' => 'WF',
				'iso_alpha3' => 'WLF',
				'iso_numeric' => '876',
				'currency_code' => 'XPF',
				'currency_name' => 'Franc',
				'currrency_symbol' => NULL,
				'flag' => 'WF.png',
			),
			235 => 
			array (
				'id' => '236',
				'name' => 'Western Sahara',
				'iso_alpha2' => 'EH',
				'iso_alpha3' => 'ESH',
				'iso_numeric' => '732',
				'currency_code' => 'MAD',
				'currency_name' => 'Dirham',
				'currrency_symbol' => NULL,
				'flag' => 'EH.png',
			),
			236 => 
			array (
				'id' => '237',
				'name' => 'Yemen',
				'iso_alpha2' => 'YE',
				'iso_alpha3' => 'YEM',
				'iso_numeric' => '887',
				'currency_code' => 'YER',
				'currency_name' => 'Rial',
				'currrency_symbol' => '﷼',
				'flag' => 'YE.png',
			),
			237 => 
			array (
				'id' => '238',
				'name' => 'Zambia',
				'iso_alpha2' => 'ZM',
				'iso_alpha3' => 'ZMB',
				'iso_numeric' => '894',
				'currency_code' => 'ZMK',
				'currency_name' => 'Kwacha',
				'currrency_symbol' => 'ZK',
				'flag' => 'ZM.png',
			),
			238 => 
			array (
				'id' => '239',
				'name' => 'Zimbabwe',
				'iso_alpha2' => 'ZW',
				'iso_alpha3' => 'ZWE',
				'iso_numeric' => '716',
				'currency_code' => 'ZWD',
				'currency_name' => 'Dollar',
				'currrency_symbol' => 'Z$',
				'flag' => 'ZW.png',
			),
		));
	}

}
